language: node_js
node_js:
  - 0.10
  - 4
  - 8
  - 10
  - 12
  - 13
before_install:
  - npm install -g qnit
  - sudo apt-get install php5-cli
after_success:
  - if [ `node -p 'process.version.slice(0, 3)'` != "v8." ]; then exit; fi
  - npm install -g nyc coveralls
  - nyc --reporter lcov -r text npm test
  - nyc report -r text-lcov | coveralls
